FROM openjdk:21-jdk-slim

LABEL author="Ana Silva"

WORKDIR /ca4-part1

COPY . /ca4-part1

RUN apt-get update && apt-get install -y dos2unix

RUN dos2unix ./gradlew

RUN chmod +x gradlew

EXPOSE 59001

CMD ["./gradlew", "runServer"]